import React, { useState, useEffect } from 'react';
import {
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Alert,
  Box,
  Typography,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Grid,
  Divider,
  Button,
  IconButton,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions
} from '@mui/material';
import ExpandMoreIcon from '@mui/icons-material/ExpandMore';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';

/**
 * ProfileForm Component
 *
 * Form fields for profile name and algorithm selection.
 * Includes validation for name uniqueness and profile count limits.
 *
 * @param {Object} props
 * @param {Object} props.formData - Current form data
 * @param {Function} props.onChange - Callback when form data changes
 * @param {string} props.mode - 'create' or 'edit'
 */
function ProfileForm({ formData, onChange, mode }) {
  const [errors, setErrors] = useState({});
  const [existingNames, setExistingNames] = useState([]);
  const [profileCount, setProfileCount] = useState(0);
  const [addClaimDialogOpen, setAddClaimDialogOpen] = useState(false);
  const [newClaimName, setNewClaimName] = useState('');
  const [newClaimValue, setNewClaimValue] = useState('');

  useEffect(() => {
    // Load existing profile names and count for validation
    loadProfileInfo();
  }, []);

  /**
   * Load existing profile information for validation
   */
  const loadProfileInfo = async () => {
    try {
      const profiles = await window.electronAPI.loadProfiles();
      if (profiles.success) {
        setExistingNames(profiles.data.map(p => p.name));
        setProfileCount(profiles.data.length);
      }
    } catch (error) {
      // Profile info loading failure handled - validation will still work
    }
  };

  const validateName = (name) => {
    const newErrors = { ...errors };

    if (!name || name.trim().length === 0) {
      newErrors.name = 'Profile name is required';
    } else if (name.length > 50) {
      newErrors.name = 'Profile name must be 50 characters or less';
    } else if (
      existingNames.includes(name) &&
      (mode === 'create' || name !== formData.name)
    ) {
      newErrors.name = 'A profile with this name already exists';
    } else {
      delete newErrors.name;
    }

    setErrors(newErrors);
    return !newErrors.name;
  };

  const handleNameChange = (e) => {
    const name = e.target.value;
    validateName(name);
    onChange({
      ...formData,
      name
    });
  };

  const handleAlgorithmChange = (e) => {
    const algorithm = e.target.value;
    onChange({
      ...formData,
      algorithm,
      key: '' // Clear key when algorithm changes
    });
  };

  const handlePayloadFieldChange = (fieldName, value) => {
    const updatedPayload = {
      ...(formData.payload || {}),
      [fieldName]: value
    };
    onChange({
      ...formData,
      payload: updatedPayload
    });
  };

  const handleAddClaim = () => {
    const claimName = newClaimName.trim();

    // Validation
    if (!claimName) return;

    // Check for reserved field names
    const reservedFields = ['exp', 'iat', 'nbf'];
    if (reservedFields.includes(claimName)) {
      alert(`"${claimName}" is a reserved field name and will be auto-generated.`);
      return;
    }

    // Check for duplicate field names
    if (formData.payload && formData.payload.hasOwnProperty(claimName)) {
      alert(`Claim "${claimName}" already exists.`);
      return;
    }

    // Validate field name format (alphanumeric, underscore, hyphen)
    if (!/^[a-zA-Z0-9_-]+$/.test(claimName)) {
      alert('Claim name must contain only letters, numbers, underscores, and hyphens.');
      return;
    }

    // Add the claim
    const updatedPayload = {
      ...(formData.payload || {}),
      [claimName]: newClaimValue
    };
    onChange({
      ...formData,
      payload: updatedPayload
    });

    // Reset dialog
    setNewClaimName('');
    setNewClaimValue('');
    setAddClaimDialogOpen(false);
  };

  const handleRemoveClaim = (claimName) => {
    const updatedPayload = { ...(formData.payload || {}) };
    delete updatedPayload[claimName];
    onChange({
      ...formData,
      payload: updatedPayload
    });
  };

  // Get all claim field names from payload (excluding auto-generated ones)
  const autoGeneratedFields = ['exp', 'iat', 'nbf'];
  const claimFieldNames = Object.keys(formData.payload || {}).filter(
    key => !autoGeneratedFields.includes(key)
  );

  // Check if profile limit is reached for create mode
  const isProfileLimitReached = mode === 'create' && profileCount >= 50;

  return (
    <Box sx={{ display: 'flex', flexDirection: 'column', gap: 3, py: 1 }}>
      {isProfileLimitReached && (
        <Alert severity="error">
          Maximum profile limit (50) reached. Please delete an existing profile
          before creating a new one.
        </Alert>
      )}

      <TextField
        label="Profile Name"
        value={formData.name}
        onChange={handleNameChange}
        error={!!errors.name}
        helperText={errors.name || 'Enter a unique name for this profile (1-50 characters)'}
        fullWidth
        required
        disabled={isProfileLimitReached}
        inputProps={{
          maxLength: 50,
          'data-testid': 'profile-name-input'
        }}
      />

      <FormControl fullWidth required disabled={isProfileLimitReached}>
        <InputLabel id="algorithm-label">Algorithm</InputLabel>
        <Select
          labelId="algorithm-label"
          value={formData.algorithm}
          onChange={handleAlgorithmChange}
          label="Algorithm"
          data-testid="profile-algorithm-select"
        >
          <MenuItem value="HS256">HS256 (HMAC with SHA-256)</MenuItem>
          <MenuItem value="RS256">RS256 (RSA with SHA-256)</MenuItem>
        </Select>
        <Typography variant="caption" color="text.secondary" sx={{ mt: 1 }}>
          {formData.algorithm === 'HS256'
            ? 'Use a Base64-encoded secret key for HS256'
            : 'Use a PEM-encoded RSA private key for RS256'}
        </Typography>
      </FormControl>

      <TextField
        label="Signing Key"
        value={formData.key || ''}
        onChange={(e) => onChange({ ...formData, key: e.target.value })}
        multiline
        rows={4}
        fullWidth
        required
        disabled={isProfileLimitReached}
        helperText={
          formData.algorithm === 'HS256'
            ? 'Enter Base64-encoded secret key'
            : 'Enter PEM-encoded RSA private key (BEGIN/END markers required)'
        }
        inputProps={{
          'data-testid': 'profile-key-input'
        }}
      />

      {mode === 'edit' && formData.key && (
        <Alert severity="info">
          The key is encrypted at rest. Changing the key will re-encrypt it.
        </Alert>
      )}

      <Divider sx={{ my: 3 }} />

      <Accordion defaultExpanded={false} disabled={isProfileLimitReached}>
        <AccordionSummary
          expandIcon={<ExpandMoreIcon />}
          aria-controls="profile-claims-content"
          id="profile-claims-header"
        >
          <Box>
            <Typography variant="subtitle1" sx={{ fontWeight: 600 }}>
              Profile Claims (Optional)
            </Typography>
            <Typography variant="caption" color="text.secondary">
              Define default JWT claims for this profile. These will auto-populate when using this profile.
            </Typography>
          </Box>
        </AccordionSummary>
        <AccordionDetails>
          <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
            <Typography variant="body2" color="text.secondary">
              {claimFieldNames.length} claim{claimFieldNames.length !== 1 ? 's' : ''}
            </Typography>
            <Button
              startIcon={<AddIcon />}
              variant="outlined"
              size="small"
              onClick={() => setAddClaimDialogOpen(true)}
              data-testid="add-profile-claim-button"
            >
              Add Claim
            </Button>
          </Box>

          {claimFieldNames.length === 0 ? (
            <Box sx={{ py: 3, textAlign: 'center' }}>
              <Typography variant="body2" color="text.secondary">
                No claims defined. Click "Add Claim" to add custom JWT claims.
              </Typography>
            </Box>
          ) : (
            <Grid container spacing={2}>
              {claimFieldNames.map((claimName) => (
                <Grid item xs={12} sm={6} key={claimName}>
                  <Box sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
                    <TextField
                      fullWidth
                      label={claimName}
                      value={formData.payload[claimName] || ''}
                      onChange={(e) => handlePayloadFieldChange(claimName, e.target.value)}
                      placeholder={`Value for ${claimName}`}
                      data-testid={`profile-claim-${claimName}`}
                    />
                    <IconButton
                      size="small"
                      color="error"
                      onClick={() => handleRemoveClaim(claimName)}
                      sx={{ mt: 1 }}
                      data-testid={`remove-claim-${claimName}`}
                      aria-label={`Remove ${claimName}`}
                    >
                      <DeleteIcon />
                    </IconButton>
                  </Box>
                </Grid>
              ))}
            </Grid>
          )}

          <Alert severity="info" sx={{ mt: 2 }}>
            These default values can be overridden in the Token Configuration when generating tokens.
            Fields like 'exp', 'iat', and 'nbf' are auto-generated.
          </Alert>
        </AccordionDetails>
      </Accordion>

      {/* Add Claim Dialog */}
      <Dialog
        open={addClaimDialogOpen}
        onClose={() => setAddClaimDialogOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Add Custom Claim</DialogTitle>
        <DialogContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
            <TextField
              label="Claim Name"
              value={newClaimName}
              onChange={(e) => setNewClaimName(e.target.value)}
              placeholder="e.g., userId, role, customerId"
              helperText="Alphanumeric, underscore, and hyphen allowed"
              fullWidth
              autoFocus
              data-testid="claim-name-input"
            />
            <TextField
              label="Claim Value"
              value={newClaimValue}
              onChange={(e) => setNewClaimValue(e.target.value)}
              placeholder="Enter default value"
              helperText="This value will be used by default when generating tokens"
              fullWidth
              data-testid="claim-value-input"
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setAddClaimDialogOpen(false)}>Cancel</Button>
          <Button
            onClick={handleAddClaim}
            variant="contained"
            disabled={!newClaimName.trim()}
            data-testid="confirm-add-claim"
          >
            Add
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}

export default ProfileForm;
