import React, { useState } from 'react';
import {
  TextField,
  Grid,
  Button,
  IconButton,
  Box,
  Typography,
  Divider,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions
} from '@mui/material';
import AddIcon from '@mui/icons-material/Add';
import DeleteIcon from '@mui/icons-material/Delete';

/**
 * FormMode Component
 *
 * Form-based payload editing with common JWT claim fields.
 * Allows adding and removing custom fields.
 */
export default function FormMode({ payload, onUpdateField, onAddCustomField, onRemoveField }) {
  const [addFieldDialogOpen, setAddFieldDialogOpen] = useState(false);
  const [newFieldName, setNewFieldName] = useState('');
  const [newFieldValue, setNewFieldValue] = useState('');

  // Common JWT claim fields
  const commonFields = [
    { name: 'userId', label: 'User ID', type: 'text' },
    { name: 'username', label: 'Username', type: 'text' },
    { name: 'email', label: 'Email', type: 'email' },
    { name: 'roleCode', label: 'Role Code', type: 'text' },
    { name: 'merchantId', label: 'Merchant ID', type: 'text' },
    { name: 'sub', label: 'Subject (sub)', type: 'text' },
    { name: 'iss', label: 'Issuer (iss)', type: 'text' },
    { name: 'aud', label: 'Audience (aud)', type: 'text' }
  ];

  // Identify custom fields (not in common fields list and not auto-generated)
  const autoGeneratedFields = ['exp', 'iat', 'nbf'];
  const commonFieldNames = commonFields.map(f => f.name);
  const customFieldNames = Object.keys(payload).filter(
    key => !commonFieldNames.includes(key) && !autoGeneratedFields.includes(key)
  );

  const handleAddCustomField = () => {
    if (newFieldName && newFieldName.trim() !== '') {
      const success = onAddCustomField(newFieldName.trim(), newFieldValue);
      if (success) {
        setNewFieldName('');
        setNewFieldValue('');
        setAddFieldDialogOpen(false);
      }
    }
  };

  return (
    <Box>
      <Typography variant="h6" gutterBottom>
        Common Claims
      </Typography>

      <Grid container spacing={2}>
        {commonFields.map((field) => (
          <Grid item xs={12} sm={6} key={field.name}>
            <TextField
              fullWidth
              label={field.label}
              type={field.type}
              value={payload[field.name] || ''}
              onChange={(e) => onUpdateField(field.name, e.target.value)}
              data-testid={`payload-field-${field.name}`}
            />
          </Grid>
        ))}
      </Grid>

      <Divider sx={{ my: 3 }} />

      <Box sx={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', mb: 2 }}>
        <Typography variant="h6">
          Custom Fields
        </Typography>
        <Button
          startIcon={<AddIcon />}
          variant="outlined"
          size="small"
          onClick={() => setAddFieldDialogOpen(true)}
          data-testid="add-custom-field-button"
        >
          Add Custom Field
        </Button>
      </Box>

      {customFieldNames.length === 0 ? (
        <Typography variant="body2" color="text.secondary">
          No custom fields. Click "Add Custom Field" to add one.
        </Typography>
      ) : (
        <Grid container spacing={2}>
          {customFieldNames.map((fieldName) => (
            <Grid item xs={12} sm={6} key={fieldName}>
              <Box sx={{ display: 'flex', gap: 1, alignItems: 'flex-start' }}>
                <TextField
                  fullWidth
                  label={fieldName}
                  value={payload[fieldName] || ''}
                  onChange={(e) => onUpdateField(fieldName, e.target.value)}
                  data-testid={`custom-field-${fieldName}`}
                />
                <IconButton
                  size="small"
                  color="error"
                  onClick={() => onRemoveField(fieldName)}
                  sx={{ mt: 1 }}
                  data-testid={`remove-field-${fieldName}`}
                >
                  <DeleteIcon />
                </IconButton>
              </Box>
            </Grid>
          ))}
        </Grid>
      )}

      <Divider sx={{ my: 3 }} />

      <Typography variant="caption" color="text.secondary">
        Note: Fields like 'exp' (expiration) and 'iat' (issued at) are auto-generated during token creation.
      </Typography>

      {/* Add Custom Field Dialog */}
      <Dialog
        open={addFieldDialogOpen}
        onClose={() => setAddFieldDialogOpen(false)}
        maxWidth="sm"
        fullWidth
      >
        <DialogTitle>Add Custom Field</DialogTitle>
        <DialogContent>
          <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, pt: 1 }}>
            <TextField
              label="Field Name"
              value={newFieldName}
              onChange={(e) => setNewFieldName(e.target.value)}
              placeholder="e.g., customerId"
              helperText="Alphanumeric, underscore, and hyphen allowed"
              fullWidth
              autoFocus
            />
            <TextField
              label="Field Value"
              value={newFieldValue}
              onChange={(e) => setNewFieldValue(e.target.value)}
              placeholder="Enter value"
              fullWidth
            />
          </Box>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setAddFieldDialogOpen(false)}>Cancel</Button>
          <Button
            onClick={handleAddCustomField}
            variant="contained"
            disabled={!newFieldName.trim()}
          >
            Add
          </Button>
        </DialogActions>
      </Dialog>
    </Box>
  );
}
